<!DOCTYPE html>
<html lang="hu">
<head>
    <meta charset="UTF-8">
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <link rel="stylesheet" href="Nav.css">
    <title>Allatfeltoltes</title>
</head>
<body>

<div id = "nav-placeholder">
</div>

<script>
    $(function(){
        $("#nav-placeholder").load("lognavbar.html");
    });
</script>

<br>
<br>
<br>

<div class="container">
    <form action="./allat.php" method="POST">
        <h1><label>Nev</label></h1>
        <input name="name" type=text required placeholder="name">
        <h1><label>Faj</label></h1>
        <input name="species" type=text required placeholder="species">
        <h1><label>Nem</label></h1>
        <input name="sex" type=text required placeholder="sex">
        <h1><label>Leiras</label></h1>
        <input name="descr" type=text required placeholder="desc">
        <h1><label>Szuletesi ev</label></h1>
        <input name="age" type=number min="1900" max="2012" required placeholder="Szuletesi ev">
        <h1><label>Kep eleresi utvonala</label></h1>
        <input name="pic" type=text required placeholder="Utvonal">
        <br>
        <input type=submit  value="Hozzaad" name="Hozzaad">
    </form>

</div>


<script type="application/javascript">
    function saveAndOpenPage() {
        trySave();
        window.location.href = 'login.html';
        alert("Jelentkezz be!")
    }
    function trySave()
    {
        const uName = document.getElementById("userName").value;
        const password = document.getElementById("password").value;
        const lName = document.getElementById("lastName").value;
        const fName = document.getElementById("firstName").value;
        const email = document.getElementById("email").value;
        const age = document.getElementById("age").value;

        if(lName && fName && email && uName && password) {
            const xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (xhttp.readyState == 4 && xhttp.status == 200) {
                    const result = JSON.parse(xhttp.responseText);
                    console.log(result);
                    alert("Sikeres mentes!");


                }
            }
            const params = new URLSearchParams(
                {
                    "userName":uName,
                    "password":password,
                    "firstName": fName,
                    "lastName": lName,
                    "email": email,
                    "age": age
                })
            xhttp.open("GET", "./connect.php?" + params.toString());
            xhttp.send();
        }
        else
        {
            alert("Minden mezot tolts ki!");
        }

    }</script>

</body>
</html>