<!DOCTYPE html>
<!-- #include virtual="../navbar.html"-->


<html lang="hu" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="Nav.css">
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>


    <title>Kezdőlap</title>

</head>
<body background="kepek/hatter.jpg">


<div id = "nav-placeholder">
</div>

<?php
session_start();
if(isset($_SESSION['user']))
    $username = $_SESSION['user'];
else
    $username = NULL;


if(isset($_SESSION['user']) == NULL)
{
    ?>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <center><font size="20">Regisztrálj most az oldalunkra</font></center>
    <br>
    <br>
    <br>
    <center><a href="register.html"><button  type="button">Regisztráció</button></a></center>

   <script>
        $(function(){
            $("#nav-placeholder").load("navbar.html");
        });
    </script>
    <?php
}
else
{
    ?>
<br>
<br>
<br>
<br>
<br>
<br>
<center><font size="20">Udvozlunk felhasznalo!</font></center>
    <script>
        $(function(){
            $("#nav-placeholder").load("lognavbar.html");
        });
    </script>
<?php
}

?>
<!---->

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>






</body>
</html>