<!DOCTYPE html>
<html lang="hu">

<?php
$connect = mysqli_connect("localhost","root","") or die ("Couldn't connect!");
mysqli_select_db($connect,'users') or die ("Couldn't find db");
$q = mysqli_query($connect,"SELECT * FROM users");

while ($r = mysqli_fetch_assoc($q))
{
    $id = $r['id'];
    $username = $r['username'];
    $firstname = $r['firstname'];
    $lastname = $r['lastname'];
    $age = $r['age'];
    $email = $r['email'];
    $password = $r['password'];
}

?>
<head>
    <meta charset="UTF-8">
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <link rel="stylesheet" href="Nav.css">
    <div id = "nav-placeholder">
    <title><?php echo $username; ?></title>
    <?php
    session_start();
    if(isset($_SESSION['user']))
        $username = $_SESSION['user'];
    else
        $username = NULL;


    if(isset($_SESSION['user']) == NULL)
    {
        ?>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
        <center><font size="20">Regisztrálj most az oldalunkra</font></center>
    <br>
    <br>
    <br>
        <center><a href="register.html"><button  type="button">Regisztráció</button></a></center>

        <script>
            $(function(){
                $("#nav-placeholder").load("navbar.html");
            });
        </script>
    <?php
    }
    else
    {
    ?>

        <center><font size="20">Udvozlunk felhasznalo!</font></center>
        <script>
            $(function(){
                $("#nav-placeholder").load("lognavbar.html");
            });
        </script>
        <?php
    }

    ?>
    </div>
</head>
<body>

<br>
<br>
<br>
<br>

<h1><label>Felhasznalo</label></h1>
<div class="profil">
<div class="container">

    <h2><label>Felhasznalonev</label></h2>
    <input name="userName" type=text required placeholder="Felhasznalonev" value="<?php echo $username; ?>" disabled>
    <h2><label>Vezeteknev</label></h2>
    <input name="lastName" type=text required placeholder="Vezeteknev" value="<?php echo $lastname; ?>" disabled>
    <h2><label>Keresztnev</label></h2>
    <input name="firstName" type=text required placeholder="Keresztnev" value="<?php echo $firstname; ?>" disabled>
    <h2><label>Email-cim</label></h2>
    <input name="email" type=email required placeholder="Email-cim" value="<?php echo $email; ?>"disabled>
    <h2><label>Szuletesi ev</label></h2>
    <input name="age" type=number min="1900" max="2012" value="<?php echo $age; ?>" required placeholder="Szuletesi ev" disabled>

</div>
</div>

<button onclick="window.location.href='allatfeltoltes.phtml'">Allatfeltoltes</button>
</body>
</html>